{
  "name": "WorldReset",
  "main": "com.github.fefo.worldreset.WorldResetPlugin",
  "version": "${pluginVersion}",
  "api-version": "1.13",
  "load": "STARTUP",
  "authors": [
    "Fefo"
  ],

  "permissions": {
    "worldreset.receivebroadcast": {
      "default": true
    },
    "worldreset.command": {
      "default": "op"
    }
  },
}
